from Z2Funcoes_Troca_Senha import*
#INVOCANDO FUNÇÃO PARA ABRIR O CAMPO DE INSERIR OS DADOS
Clicando_Para_Logar
#INVOCANDO FUNÇÃO PARA INSERIR E-MAIL E SENHA
Inserindo_Email_Senha
sleep(5)
#INVOCANDO FUNÇÕES PARA INSERIR AS PERMISSÕES NECESSARIAS PRO APLICATIVO
Aceitando_Permissoes
Permissao_Local
Permissao_All_Time
###############################################LOGIN CONCLUIDO
#INVOCANDO FUNÇÃO PARA IR PARA TELA DE PERFIL
Botao_Profile
#INVOCANDO FUNÇÃO PARA EDITAR PERFIL
Clickando_EditarPerfil
#INVOCANDO FUNÇÃO PARA INSERIR SENHA ATUAL,NOVA E CONFIRMAR A SENHA NOVA
Preenchendo_Troca_Senha


#Fim